import test from 'node:test';
import assert from 'node:assert/strict';
import {handleGlobalDemo} from '../server/global-demo.mjs';
import {GOOGLE_SUITE_CLIENT_ID} from '../server/demo-session.mjs';
function database(){const rows=new Map();return {rows,prepare(sql){let values;return {bind(...v){values=v;return this;},async first(){return rows.get(values[0])||null;},async run(){if(sql.startsWith('INSERT')){if(rows.has(values[0]))return {meta:{changes:0}};rows.set(values[0],{project_id:values[0],playlist_id:null,title:values[1]});}if(sql.startsWith('UPDATE'))Object.assign(rows.get(values[2]),{playlist_id:values[0],owner_token:values[1]});return {meta:{changes:1}};}};}};}
const request=(method='GET',body,token)=>new Request('https://www.admira.biz/api/demo-global?project=sneakers-store',{method,headers:token?{Authorization:'Bearer '+token}:{},body:body?JSON.stringify(body):undefined});
test('authenticated creation keeps ownership server-side and reuses the existing project playlist',async()=>{const db=database();let creates=0;const fetcher=async(url,init)=>{if(url.includes('tokeninfo'))return Response.json({aud:GOOGLE_SUITE_CLIENT_ID,iss:'accounts.google.com',sub:'user',exp:Date.now()/1000+1000,email_verified:true,email:'csilvasantin@gmail.com'});if(url.includes('pixeria/search'))return Response.json({total:1,items:[{id:'clip-'+new URL(url).searchParams.get('query'),title:'Stock clip',url:'https://stock.admira.store/stock/clip/asset.mp4'}]});if(url.endsWith('/playlists')){creates++;return Response.json({playlist_id:'playlist-uuid',id:'#playlistuuid',tracks:JSON.parse(init.body).tracks,revision:1,owner_token:'private-owner-token'});}return Response.json({id:'#playlistuuid',tracks:[],revision:1});};
 const body={title:'Sneakers Store',stock_ids:[990,964]};const first=await handleGlobalDemo(request('POST',body,'valid'),{ORDERS_DB:db},fetcher);assert.equal(first.status,201);assert.equal((await first.text()).includes('private-owner-token'),false);assert.equal(db.rows.get('sneakers-store').owner_token,'private-owner-token');const second=await handleGlobalDemo(request('POST',body,'valid'),{ORDERS_DB:db},fetcher);assert.equal((await second.json()).already_present,true);assert.equal(creates,1);const read=await handleGlobalDemo(request(),{ORDERS_DB:db},fetcher);assert.equal((await read.text()).includes('private-owner-token'),false);
});
test('creation refuses missing identity, unapproved Gmail, malformed project and unknown Stock',async()=>{const db=database();assert.equal((await handleGlobalDemo(request('POST',{title:'Demo',stock_ids:[990]}),{ORDERS_DB:db})).status,401);const no=async()=>Response.json({aud:GOOGLE_SUITE_CLIENT_ID,iss:'accounts.google.com',sub:'other',exp:Date.now()/1000+1000,email_verified:true,email:'someone@gmail.com'});assert.equal((await handleGlobalDemo(request('POST',{title:'Demo',stock_ids:[990]},'token'),{ORDERS_DB:db},no)).status,401);assert.equal((await handleGlobalDemo(new Request('https://www.admira.biz/api/demo-global?project=../invalid'),{ORDERS_DB:db})).status,400);assert.equal(db.rows.size,0);});
