const $=id=>document.getElementById(id),PROJECT='sneakers-store',LOCATION='sneakers-store-santa-rosa-19',TWIN='https://www.admira.store/xpacios/sneakerstore/',API='/api/demo-global?project='+PROJECT;
let en=new URLSearchParams(location.search).get('lang')==='en',step=0,timer=null,playlist=null,loc=null,central=null,issue='',generation=0;
const t=(es,english)=>en?english:es;
const steps=[
 {es:'Proyecto',en:'Project',title:['Un proyecto común.','One shared project.'],description:['El proyecto nace en el registro central y admira.biz lo utiliza para organizar sus locales.','The project starts in the central registry; admira.biz uses it to organize its venues.'],instructions:[['En admira.biz, abre Backoffice y conecta con AdmiraNext.','In admira.biz, open Backoffice and connect to AdmiraNext.'],['En «Gestionar proyectos y locales», crea Sneakers Store con ID sneakers-store y circuito sneakerstore.','In “Manage projects and venues”, create Sneakers Store, ID sneakers-store, circuit sneakerstore.'],['Conserva el ID: mapa, playlist y gemelo lo comparten. Al repetir, selecciona el proyecto existente.','Keep the ID: map, playlist and twin share it. On repeat visits, select the existing project.']],url:'https://www.admiranext.com/xpace/manage',link:['Abrir registro de proyectos ↗','Open project registry ↗']},
 {es:'Xpacio',en:'Xpace',title:['Santa Rosa 19.','Santa Rosa 19.'],description:['El local tiene su propia ficha, dirección, coordenadas y pantalla virtual.','The venue has its own record, address, coordinates and virtual screen.'],instructions:[['Abre Backoffice → Nuevo Xpacio. Nombre: Sneakers Store · Santa Rosa 19.','Open Backoffice → New Xpace. Name: Sneakers Store · Santa Rosa 19.'],['Dirección: Carrer de Santa Rosa, 19 · 08012 Barcelona. Busca coordenadas y revisa el mapa.','Address: Carrer de Santa Rosa, 19 · 08012 Barcelona. Find coordinates and review the map.'],['Asocia el gemelo SneakerStore, guarda y publica. En el registro central, asocia este local a sneakers-store.','Link the SneakerStore twin, save and publish. In the central registry, link this venue to sneakers-store.']],url:'/backoffice',link:['Abrir ficha de Xpacios ↗','Open Xpace records ↗']},
 {es:'Playlist',en:'Playlist',title:['Pixeria en la pantalla.','Pixeria on screen.'],description:['Una playlist compartida, creada desde admira.biz con vídeos publicados de Pixeria.','A shared playlist created from admira.biz using published Pixeria videos.'],instructions:[['Selecciona contenidos de Stock: #990 (anuncio Xtore) y #964 (clip de la captura).','Select Stock content: #990 (Xtore ad) and #964 (clip from the screenshot).'],['Crea la playlist una sola vez. El ID compartido se conserva en el servidor.','Create the playlist once. The shared ID stays on the server.'],['Pulsa cada pieza para verla. El gemelo lee esta misma playlist, sin copiar los vídeos.','Click a piece to preview it. The twin reads this same playlist without copying the videos.']],url:'https://www.pixeria.com/stock.html?tag=xtore',link:['Abrir Stock de Pixeria ↗','Open Pixeria Stock ↗']},
 {es:'Gemelo',en:'Twin',title:['Entrar en SneakerStore.','Enter SneakerStore.'],description:['La tienda real de Santa Rosa 19 en 360, con planta 3D editable y playlist conectada.','The real Santa Rosa 19 store in 360, with an editable 3D floor plan and a connected playlist.'],instructions:[['Abre admira.store → SneakerStore → Sneakers Store.','Open admira.store → SneakerStore → Sneakers Store.'],['Recorre Entrada, Centro y Fondo. En Planta 3D, desde puerta hacia caja: LCD a la izquierda y recreativas a la derecha. Ver pantalla abre la playlist.','Explore Entrance, Centre and Rear. In 3D floor plan, from door towards checkout: LCD on the left, arcades on the right. View screen opens the playlist.'],['Opciones a la izquierda, Avanzado a la derecha, Experto abajo. /distribuir permite editar el mobiliario.','Options on the left, Advanced on the right, Expert below. /distribuir edits the furniture.']],url:TWIN,link:['Abrir gemelo completo ↗','Open full twin ↗']},
 {es:'Cámara y guía',en:'Camera & guide',title:['La tienda responde.','The store responds.'],description:['Conecta la cámara real durante la presentación y conserva la receta para el siguiente proyecto.','Connect the real camera during the presentation and keep the recipe for the next project.'],instructions:[['En IEU: Store → Entrada → Puerta Cam → Ver stream.','In IEU: Store → Entrada → Puerta Cam → View stream.'],['Vuelve a admira.tv/videoanalytics/xtore y comparte esa pestaña. Marca dos esquinas para la zona de cámara; iPad y pantalla son opcionales.','Return to admira.tv/videoanalytics/xtore and share that tab. Mark two corners for the camera area; iPad and screen are optional.'],['Comprueba detección y player. Descarga la guía, cambia nombres e IDs y repite el proceso para el próximo proyecto.','Check detection and player. Download the guide, change names and IDs, and repeat for the next project.']],url:'https://admira.tv/videoanalytics/xtore/',link:['Abrir analítica y player ↗','Open analytics & player ↗']}
];
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function link(url,label){const a=el('a',label,'button');a.href=url.startsWith(TWIN)?url+'?lang='+(en?'en':'es'):url;a.target='_blank';a.rel='noopener';return a;}
function stop(){clearTimeout(timer);timer=null;$('tour').textContent=t('▶ Recorrido','▶ Walkthrough');}
async function check(){issue='';const results=await Promise.allSettled([fetch(API,{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('playlist '+r.status);return r.json();}),fetch('https://brain.digitalavatar.ai/locations/'+LOCATION,{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Xpacio '+r.status);return r.json();}),fetch('https://www.admiranext.com/api/xpace/demos',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('registry '+r.status);return r.json();})]);
 if(results[0].status==='fulfilled')playlist=results[0].value.playlist;else issue=String(results[0].reason.message);
 if(results[1].status==='fulfilled')loc=results[1].value;else loc=null;
 if(results[2].status==='fulfilled')central=results[2].value;render();}
async function create(){const b=$('create-playlist');b.disabled=true;try{let saved;try{saved=JSON.parse(localStorage.getItem('omnip-bo-gtoken')||sessionStorage.getItem('omnip-bo-gtoken')||'null');}catch{}if(!saved?.token)throw Error(t('Entra primero en Backoffice con Google y vuelve aquí.','Sign in to Backoffice with Google first, then return here.'));const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+saved.token},body:JSON.stringify({title:'Sneakers Store · Santa Rosa 19',stock_ids:[990,964]})});const data=await r.json();if(!r.ok)throw Error(data.error);await check();}catch(e){issue=e.message;render();}}
function render(){generation++;const s=steps[step];document.documentElement.lang=en?'en':'es';$('steps').setAttribute('aria-label',t('Pasos de la demo','Demo steps'));$('preview').setAttribute('aria-label',t('Resultado del paso','Step result'));$('tour').textContent=timer?t('Ⅱ Pausar','Ⅱ Pause'):t('▶ Recorrido','▶ Walkthrough');$('lede').textContent=t('De un proyecto a una tienda conectada. Santa Rosa 19 · Barcelona.','From project to connected store. Santa Rosa 19 · Barcelona.');$('steps').replaceChildren(...steps.map((s,i)=>{const b=el('button',(i+1)+' · '+s[en?'en':'es']);b.setAttribute('aria-current',i===step?'step':'false');b.onclick=()=>{stop();step=i;render();};return b;}));$('number').textContent=(step+1)+' / '+steps.length;$('step-title').textContent=s.title[+en];$('description').textContent=s.description[+en];$('instructions').replaceChildren(...s.instructions.map(a=>el('li',a[+en])));$('actions').replaceChildren(link(s.url,s.link[+en]));$('previous').disabled=step===0;$('next').disabled=step===4;$('next').textContent=t('Siguiente →','Next →');const p=$('preview');p.replaceChildren();
 const card=el('div',undefined,'card');p.append(card);
 const projectExists=central?.projects?.some(p=>p.id===PROJECT);
 $('live').textContent=issue||[t('Proyecto: ','Project: ')+(projectExists?t('registrado','registered'):t('pendiente de comprobar','awaiting check')),t('Xpacio: ','Xpace: ')+(loc?t('publicado','published'):t('pendiente','pending')),t('Playlist: ','Playlist: ')+(playlist?playlist.tracks.length+t(' piezas',' pieces'):t('pendiente','pending'))].join(' · ');$('live').classList.toggle('error',!!issue);
 if(step===0){card.append(el('h2','Sneakers Store'),el('p',t('Registro central de proyectos comerciales','Central commercial project registry')),el('code','sneakers-store → sneakerstore'),el('p',projectExists?t('Proyecto disponible en el registro compartido.','Project available in the shared registry.'):t('Abre el registro para comprobar el alta.','Open the registry to check the project.')));}
 if(step===1){const l=loc?.location||loc;card.append(el('h2','Santa Rosa 19'),el('p',l?.addr||'Carrer de Santa Rosa, 19 · 08012 Barcelona'),el('code',LOCATION),el('p',l?.coords?l.coords.join(', '):t('Coordenadas pendientes de publicar.','Coordinates pending publication.')),link('https://www.admira.biz/?locationId='+LOCATION,t('Ver en el mapa ↗','Show on map ↗')));}
 if(step===2){if(!playlist){card.append(el('h2',t('Crear playlist compartida','Create shared playlist')),el('p',t('Stock #990 + #964 · vídeos ya publicados.','Stock #990 + #964 · already published videos.')));const b=el('button',t('Crear playlist en admira.biz','Create playlist in admira.biz'));b.id='create-playlist';b.onclick=create;card.append(b);}else{card.append(el('code',playlist.id));const video=el('video');video.controls=true;video.playsInline=true;video.muted=true;video.src=playlist.tracks[0]?.url||'';const list=el('ul',undefined,'tracks');playlist.tracks.forEach((track,i)=>{const li=el('li'),b=el('button',(i+1)+' · '+track.title);b.onclick=()=>{video.src=track.url;video.play().catch(()=>{});list.querySelectorAll('button').forEach(x=>x.setAttribute('aria-current',String(x===b)));};li.append(b);list.append(li);});card.append(video,list);}}
 if(step===3){card.remove();const frame=el('iframe');frame.title=t('Sneakers Store · tienda real 360','Sneakers Store · real store 360');frame.src=TWIN+'?embed=1&lang='+(en?'en':'es');frame.allow='autoplay; fullscreen';p.append(frame);}
 if(step===4){card.append(el('h2',t('Preparación manual de la cámara','Manual camera preparation')),el('p',t('El gemelo de IEU se mantiene en una pestaña independiente. Su apertura automática depende del equipo de IEU.','The IEU twin stays in a separate tab. Automatic camera opening depends on the IEU team.')),link('https://digitaltwin.ieu.ai/',t('1 · Abrir IEU ↗','1 · Open IEU ↗')),el('p',t('Después comparte la pestaña desde Xtore y ajusta el encuadre.','Then share the tab from Xtore and adjust the camera area.')));const b=el('button',t('Descargar guía reutilizable','Download reusable guide'));b.onclick=exportGuide;card.append(b);}
 $('scope').textContent=t('Recorrido de altas reales y guía reproducible. La cámara de IEU se abre y comparte manualmente; compartir pantalla requiere el permiso del navegador.','Walkthrough of real records and reproducible guide. Open and share the IEU camera manually; screen sharing requires browser permission.');}
function exportGuide(){const data={schema:'admira-global-demo/v1',template_for_next_project:{project_id:'REPLACE-project-id',name:'REPLACE-project-name',circuit:'REPLACE-circuit-id',location_id:'REPLACE-location-id',address:'REPLACE-address',twin_url:'REPLACE-own-twin-url',stock_ids:[990,964]},reference:{project_id:PROJECT,location_id:LOCATION,twin_url:TWIN,playlist_id:playlist?.id||null},steps:steps.map((s,i)=>({step:i+1,title:s.title[+en],instructions:s.instructions.map(a=>a[+en]),url:s.url})),limits:t('No importa las credenciales, no duplica altas y no provisiona automáticamente IEU ni dispositivos físicos.','Does not export credentials, duplicate records or automatically provision IEU or physical devices.')};const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download='admira-global-demo-template.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('admira:lang',e=>{en=e.detail?.lang==='en';render();});$('previous').onclick=()=>{stop();if(step>0)step--;render();};$('next').onclick=()=>{stop();if(step<4)step++;render();};$('tour').onclick=()=>{if(timer){stop();return;}const tick=()=>{if(step>=4){stop();return;}step++;render();timer=setTimeout(tick,18000);$('tour').textContent=t('Ⅱ Pausar','Ⅱ Pause');};timer=setTimeout(tick,18000);$('tour').textContent=t('Ⅱ Pausar','Ⅱ Pause');};
document.addEventListener('click',e=>{if(e.target.closest('#demo-recheck'))check();if(e.target.closest('#demo-export'))exportGuide();});window.addEventListener('pagehide',stop);render();check();
